function fnv1a(str: string): number {
  let h = 2166136261
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return h >>> 0
}

function questionIndex(leagueId: number, gw: number, slot: string): number {
  return fnv1a(`${leagueId}|${gw}|${slot}|question`)
}

export const SEASON_STORY_QUESTION_POOLS: Record<string, readonly string[]> = {
  lede: [
    "What happened this gameweek?",
    "Give me the GW recap for our league",
    "How did this gameweek play out?",
    "Summarise this week for us",
    "What is the headline from this week?",
    "Catch me up on this gameweek",
    "What went down in our league this GW?",
    "Run me through this week's action",
    "How would you describe this gameweek?",
    "What is the story of this week?",
    "Paint me a picture of this GW",
    "What stood out this gameweek?",
    "How was this week in our mini-league?",
    "Give me the opening take on GW",
    "What defined this gameweek?",
    "Set the scene for this week",
    "How did GW shape up?",
    "What is the big picture this week?",
    "Talk me through this gameweek",
    "How should I remember this week?"
  ],
  fixture: [
    "How did fixtures affect our league this week?",
    "Was this a blank or double gameweek?",
    "Did fixture swings change anything?",
    "How tough was the fixture list this GW?",
    "Who got lucky with fixtures this week?",
    "Who got punished by the schedule?",
    "What did the fixture list do to scores?",
    "Was fixture difficulty a factor this GW?",
    "How did DGW or BGW land in our league?",
    "Did anyone benefit from extra games?",
    "Did anyone suffer from missing fixtures?",
    "What should we know about fixtures this week?",
    "How did the calendar shape GW?",
    "Were fixtures the main story this week?",
    "Who had the kindest run this GW?",
    "Who had the hardest fixture week?",
    "Did blank weeks hurt anyone badly?",
    "Did doubles boost anyone's week?",
    "How did match scheduling play out?",
    "What fixture context matters this GW?"
  ],
  personality: [
    "What is the mood in our league right now?",
    "How would you describe the vibe this week?",
    "Is the league feeling competitive or flat?",
    "What is the emotional temperature in the room?",
    "Are managers playing it safe or going bold?",
    "Is there panic or confidence in the league?",
    "What kind of week was it emotionally?",
    "Are people chasing or protecting leads?",
    "Is the league getting spicy or staying calm?",
    "What is the general energy this GW?",
    "Are mini-league egos on the line?",
    "Is anyone feeling the pressure?",
    "Did this week raise the stakes?",
    "How tense is the league feeling?",
    "Are we in survival mode or all-out attack?",
    "What is the league personality this week?",
    "Is complacency setting in anywhere?",
    "Are underdogs feeling hopeful?",
    "Are favourites feeling the heat?",
    "What is the mood among managers?"
  ],
  standings: [
    "Who is leading the league?",
    "What does the table look like?",
    "Who is on top after this GW?",
    "How tight is the title race?",
    "Who is chasing the leader?",
    "What changed in the standings?",
    "Who climbed the table this week?",
    "Who slipped down the table?",
    "How does the top of the league look?",
    "Is the lead comfortable or fragile?",
    "Who is in the title picture?",
    "What are the key table positions?",
    "How far ahead is first place?",
    "Who is hanging on in the top spots?",
    "Is the league table opening up or closing?",
    "Who made ground on the leader?",
    "Who lost ground in the standings?",
    "What does the league ladder say?",
    "Who should be worried about their rank?",
    "Give me the table update"
  ],
  podium: [
    "Who made the GW podium?",
    "Who were the top three this week?",
    "Who won the gameweek?",
    "Who finished second and third?",
    "What did the podium look like?",
    "Who had the best GW score?",
    "Who joined the podium this week?",
    "Did the usual suspects top the week?",
    "Any surprises on the podium?",
    "Who stole the show this GW?",
    "Who posted the biggest GW?",
    "Who landed on the honours board?",
    "How did the top three shake out?",
    "Who led the weekly scores?",
    "Who claimed GW glory?",
    "Who were the weekly heroes?",
    "Did anyone smash it on the podium?",
    "Who topped the mini-league this GW?",
    "What were the podium scores like?",
    "Who gets bragging rights this week?"
  ],
  movement: [
    "Who were the big movers this week?",
    "Who climbed the ranks fastest?",
    "Who had the biggest rank rise?",
    "Who tumbled down the table?",
    "Any dramatic rank swings this GW?",
    "Who gained the most places?",
    "Who lost the most places?",
    "Were there any rank explosions?",
    "Who is on a hot streak up the table?",
    "Who is sliding backwards?",
    "What were the standout rank changes?",
    "Did anyone rocket up the league?",
    "Did anyone freefall this week?",
    "Who made the biggest leap?",
    "Who took the hardest rank hit?",
    "How volatile was the table this GW?",
    "Who is momentum building for?",
    "Who is losing ground quickly?",
    "Any shock rank moves?",
    "Who moved the needle most this week?"
  ],
  gap: [
    "How far am I off the lead?",
    "What is the gap to first place?",
    "Can I still catch the leader?",
    "How many points behind am I?",
    "Is the title still realistic for me?",
    "How close am I to the top?",
    "What do I need to close the gap?",
    "Am I still in the hunt?",
    "How big is the deficit to first?",
    "Is the lead slipping away from me?",
    "Am I within striking distance?",
    "How does my gap compare to last week?",
    "Did I gain or lose ground on the leader?",
    "What would it take to catch up?",
    "Am I pacing the leader or falling behind?",
    "How many managers are between me and first?",
    "Is my deficit growing or shrinking?",
    "Should I be worried about the gap?",
    "How chaseable is the lead from here?",
    "What is my path back to the top?"
  ],
  captaincy: [
    "How did captain picks land this week?",
    "Who nailed their captain choice?",
    "Who got burned by captaincy?",
    "What were the template captain calls?",
    "Did anyone go differential on the armband?",
    "Who captained wisely this GW?",
    "Who regretted their captain pick?",
    "What captain trends showed up?",
    "Did the safe picks pay off?",
    "Any rogue captains that paid off?",
    "Who followed the template?",
    "Who went against the crowd?",
    "How brutal was captaincy this week?",
    "Who got the armband right?",
    "Who left points on the bench with captaincy?",
    "What were the popular captain choices?",
    "Did the template captains perform?",
    "Who took a captain gamble?",
    "Who got the captain call wrong?",
    "Who won the captaincy battle?"
  ],
  subplots: [
    "What happened off the main story?",
    "Any mini-league subplots this week?",
    "What side stories stood out?",
    "Who had a quiet week worth noting?",
    "Any grudges brewing in the league?",
    "What drama happened behind the scores?",
    "Any funny or painful moments?",
    "What secondary stories mattered?",
    "Who had a subplot worth watching?",
    "Any league banter fuel this week?",
    "What off-pitch stories emerged?",
    "Any manager meltdowns or miracles?",
    "What happened beyond the podium?",
    "Any rivalry sparks this GW?",
    "Who became the talking point?",
    "What unexpected angles showed up?",
    "Any league inside jokes forming?",
    "What stories will managers repeat?",
    "Who had the most entertaining week?",
    "What subplots should I follow?"
  ],
  chip_verdict: [
    "How did chips play out this week?",
    "Who played a chip and was it worth it?",
    "Any wildcard or bench boost drama?",
    "Did chips deliver or flop?",
    "Who timed their chip well?",
    "Who wasted a chip this GW?",
    "What chip decisions stood out?",
    "Any triple captain hits or misses?",
    "How did chip users fare?",
    "Was anyone's chip a masterstroke?",
    "Did bench boost save or sink someone?",
    "Any free hit heroes or villains?",
    "Who rolled the dice on a chip?",
    "How brutal were chip outcomes?",
    "Did chips change the league picture?",
    "Who got maximum value from a chip?",
    "Any chip regrets this week?",
    "What chip stories defined GW?",
    "Did chips separate managers?",
    "How should we judge this week's chips?"
  ],
  hit_regret: [
    "Who took hits and regretted it?",
    "Any transfer hits backfire this week?",
    "Who paid the price for transfers?",
    "Were hits worth it this GW?",
    "Who took a minus four and why?",
    "Any hit-taking disasters?",
    "Who gambled on transfers?",
    "Did hits pay off for anyone?",
    "Who should have held their transfers?",
    "What hit decisions hurt most?",
    "Any reckless transfer moves?",
    "Who chased points with hits?",
    "How costly were transfer hits?",
    "Who lost ground because of hits?",
    "Any hit takers come out ahead?",
    "What transfer gambles flopped?",
    "Who paid for being too active?",
    "Did hits change the weekly race?",
    "Any minus eight horror stories?",
    "Who has transfer regret this week?"
  ],
  milestones: [
    "Any milestones hit this week?",
    "Who reached a big points landmark?",
    "Any records broken in the league?",
    "Who hit a personal best?",
    "Any century marks or round numbers?",
    "What milestones mattered this GW?",
    "Who joined an exclusive club?",
    "Any first-time achievements?",
    "Who passed a notable threshold?",
    "Any league records under threat?",
    "Who ticked off a season goal?",
    "Any historic GW scores?",
    "Who hit a scoring milestone?",
    "What numbers stood out this week?",
    "Any managers hit 1000+ total?",
    "Who reached a rank milestone?",
    "Any streak milestones broken?",
    "Who celebrated a landmark GW?",
    "What achievements deserve a mention?",
    "Any season-firsts this week?"
  ],
  consistency: [
    "Who is the most consistent manager?",
    "Who never misses?",
    "Who is Mr Reliable in our league?",
    "Who posts steady scores every week?",
    "Who avoids the blow-up weeks?",
    "Who is the safest pair of hands?",
    "Who keeps delivering without fuss?",
    "Who is the model of consistency?",
    "Who rarely disappoints?",
    "Who is the metronome of the league?",
    "Who avoids wild swings?",
    "Who is always in the mix?",
    "Who is the least volatile manager?",
    "Who keeps pace week after week?",
    "Who is the steady Eddie of the league?",
    "Who rarely drops a clanger?",
    "Who is the consistency king?",
    "Who should others fear every GW?",
    "Who is the most dependable scorer?",
    "Who embodies steady progress?"
  ],
  rivalry: [
    "How did my head-to-head rivalry go?",
    "Did I beat my direct rival?",
    "What happened in my key rivalry?",
    "Am I winning the personal battle?",
    "How is my rivalry streak looking?",
    "Did my rival outscore me?",
    "Who is ahead in our head-to-head?",
    "Any rivalry bragging rights this week?",
    "Did I claw one back on my rival?",
    "How tense is my rivalry right now?",
    "Who won the mini-battle this GW?",
    "Is my rival pulling away?",
    "Did I land a blow on my nemesis?",
    "What is the rivalry scoreline?",
    "Any revenge story this week?",
    "Who has the upper hand in our duel?",
    "Did rivalry points matter this GW?",
    "How did my closest rival fare?",
    "Am I building a rivalry run?",
    "What is the head-to-head update?"
  ],
  personal: [
    "How was my gameweek?",
    "How did I do this week?",
    "Give me my personal GW recap",
    "Was it a good week for me?",
    "How did my score compare?",
    "What happened in my week?",
    "Did I beat the league average?",
    "How should I feel about my GW?",
    "What went right for me?",
    "What went wrong for me?",
    "How did my rank change?",
    "Am I happy with my week?",
    "Did I outperform my rivals?",
    "What is my GW verdict?",
    "How many points did I leave on the bench?",
    "Did my transfers help or hurt?",
    "How did my captain do for me?",
    "What is my takeaway from GW?",
    "Should I be pleased or worried?",
    "Summarise my week in the league"
  ],
  spoon: [
    "Who is at the bottom this week?",
    "Who won the wooden spoon?",
    "Who had the worst GW?",
    "What happened in the basement?",
    "Who is propping up the table?",
    "Any disaster scores this week?",
    "Who had a week to forget?",
    "Who is in last place?",
    "Any managers in the doldrums?",
    "Who posted the lowest score?",
    "Who is fighting relegation vibes?",
    "What went wrong at the bottom?",
    "Any basement drama this GW?",
    "Who needs a miracle next week?",
    "Who is rock bottom right now?",
    "Any shockingly bad weeks?",
    "Who is the weekly whipping boy?",
    "What is the cellar looking like?",
    "Who escaped the bottom this week?",
    "Who is stuck at the foot of the table?"
  ],
  coda: [
    "How does the week wrap up?",
    "Any final thoughts on GW?",
    "What is the closing take?",
    "How should we remember this week?",
    "What is the last word on GW?",
    "Any parting observations?",
    "What comes next after this week?",
    "How do we sign off on GW?",
    "What is the week's final verdict?",
    "Anything else before we move on?",
    "What is the bottom line this week?",
    "How does GW set up the next one?",
    "What should managers take away?",
    "Any closing league thoughts?",
    "How would you end this recap?",
    "What is the lasting impression?",
    "Any final league notes?",
    "What is the send-off for this GW?",
    "How do we close the chapter?",
    "One last thing about this week?"
  ]
}

export function pickStoryQuestion(slot: string, gw: number, leagueId: number): string {
  const pool = SEASON_STORY_QUESTION_POOLS[slot]
  if (!pool?.length) return "Tell me about this gameweek."
  let idx = questionIndex(leagueId, gw, slot) % pool.length
  if (gw > 1) {
    const prevIdx = questionIndex(leagueId, gw - 1, slot) % pool.length
    if (idx === prevIdx) idx = (idx + 1) % pool.length
  }
  return pool[idx]
}
